// app/layout.js (Server Component)
import "./globals.css";
import NavigationBar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";
import GlobalBackground from "./components/GlobalBackground/background";
import LoaderWrapper from "./components/Loader/loaderWraper";


export const metadata = {
  title: "BPO Brigade",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <GlobalBackground />
        <LoaderWrapper>
          <NavigationBar />
          {children}
          <Footer />
        </LoaderWrapper>
      </body>
    </html>
  );
}
